# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 419de7833e4cbeafbe998940ba09e945a37042fae97db0157fa0336866e967642ce6f9a7c7b907230f05a04ab4383235b94e9715409433ad7619fca3a7cf853c

test:
  secret_key_base: a3f45321534f7d64d31b590a97baaaaa71c0b90fdcb06d03e214e8739a0f06819ae48c87b09fd7e00f2e5fff3153d6afd7a4fe9a7ef4297c57d90802e7b739b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
